<?php

return [
    [
        "user_id" => 1,
        "title" => "Monolocale moderno in centro",
        "slug" => "monolocale-moderno-in-centro",
        "rooms" => 1,
        "beds" => 1,
        "bathrooms" => 1,
        "square_meters" => 40,
        "address" => "Via Garibaldi 1, Milano",
        "latitude" => 45.4642,
        "longitude" => 9.1900,
        "image_path" => "uploads/monolocale-moderno-in-centro.jpg",
        "image_original_name" => "monolocale moderno in centro",
        "is_visible" => true
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento spazioso vicino al parco",
        "slug" => "appartamento-spazioso-vicino-al-parco",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 2,
        "square_meters" => 85,
        "address" => "Viale dei Pini 15, Milano",
        "latitude" => 45.4770,
        "longitude" => 9.1812,
        "image_path" => "uploads/appartamento-spazioso-vicino-al-parco.jpg",
        "image_original_name" => "appartamento spazioso vicino al parco",
        "is_visible" => true
    ],
    [
        "user_id" => 1,
        "title" => "Monolocale in zona storica",
        "slug" => "monolocale-in-zona-storica",
        "rooms" => 1,
        "beds" => 1,
        "bathrooms" => 1,
        "square_meters" => 35,
        "address" => "Via Dante 5, Firenze",
        "latitude" => 43.7696,
        "longitude" => 11.2558,
        "image_path" => "uploads/monolocale-in-zona-storica.jpg",
        "image_original_name" => "monolocale in zona storica",
        "is_visible" => true
    ],
    [
        "user_id" => 1,
        "title" => "Trilocale vicino al mare",
        "slug" => "trilocale-vicino-al-mare",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "square_meters" => 75,
        "address" => "Via Litoranea 10, Napoli",
        "latitude" => 40.8518,
        "longitude" => 14.2681,
        "image_path" => "uploads/trilocale-vicino-al-mare.jpg",
        "image_original_name" => "trilocale vicino al mare",
        "is_visible" => true
    ],
    [
        "user_id" => 2,
        "title" => "Attico di lusso con terrazza",
        "slug" => "attico-di-lusso-con-terrazza",
        "rooms" => 4,
        "beds" => 3,
        "bathrooms" => 2,
        "square_meters" => 130,
        "address" => "Via Roma 18, Torino",
        "latitude" => 45.0703,
        "longitude" => 7.6869,
        "image_path" => "uploads/attico-di-lusso-con-terrazza.jpg",
        "image_original_name" => "attico di lusso con terrazza",
        "is_visible" => true
    ],
    [
        "user_id" => 2,
        "title" => "Bilocale accogliente con giardino",
        "slug" => "bilocale-accogliente-con-giardino",
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "square_meters" => 60,
        "address" => "Via della Rosa 4, Pisa",
        "latitude" => 43.7167,
        "longitude" => 10.4000,
        "image_path" => "uploads/bilocale-accogliente-con-giardino.jpg",
        "image_original_name" => "bilocale accogliente con giardino",
        "is_visible" => true
    ],
    [
        "user_id" => 2,
        "title" => "Villa indipendente in campagna",
        "slug" => "villa-indipendente-in-campagna",
        "rooms" => 5,
        "beds" => 4,
        "bathrooms" => 3,
        "square_meters" => 200,
        "address" => "Via delle Colline 12, Siena",
        "latitude" => 43.3188,
        "longitude" => 11.3308,
        "image_path" => "uploads/villa-indipendente-in-campagna.jpg",
        "image_original_name" => "villa indipendente in campagna",
        "is_visible" => true
    ],
    [
        "user_id" => 2,
        "title" => "Appartamento in stile rustico",
        "slug" => "appartamento-in-stile-rustico",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "square_meters" => 90,
        "address" => "Via del Bosco 8, Arezzo",
        "latitude" => 43.4633,
        "longitude" => 11.8785,
        "image_path" => "uploads/appartamento-in-stile-rustico.jpg",
        "image_original_name" => "appartamento in stile rustico",
        "is_visible" => true
    ],
    [
        "user_id" => 3,
        "title" => "Casa al mare con piscina",
        "slug" => "casa-al-mare-con-piscina",
        "rooms" => 5,
        "beds" => 4,
        "bathrooms" => 3,
        "square_meters" => 180,
        "address" => "Via del Mare 20, Rimini",
        "latitude" => 44.0633,
        "longitude" => 12.5808,
        "image_path" => "uploads/casa-al-mare-con-piscina.jpg",
        "image_original_name" => "casa al mare con piscina",
        "is_visible" => true
    ],
    [
        "user_id" => 3,
        "title" => "Appartamento in villa storica",
        "slug" => "appartamento-in-villa-storica",
        "rooms" => 4,
        "beds" => 3,
        "bathrooms" => 2,
        "square_meters" => 150,
        "address" => "Via Castello 30, Bologna",
        "latitude" => 44.4949,
        "longitude" => 11.3426,
        "image_path" => "uploads/appartamento-in-villa-storica.jpg",
        "image_original_name" => "appartamento in villa storica",
        "is_visible" => true
    ],
    [
        "user_id" => 3,
        "title" => "Monolocale accogliente in centro",
        "slug" => "monolocale-accogliente-in-centro",
        "rooms" => 1,
        "beds" => 1,
        "bathrooms" => 1,
        "square_meters" => 45,
        "address" => "Via Verdi 15, Torino",
        "latitude" => 45.0703,
        "longitude" => 7.6869,
        "image_path" => "uploads/monolocale-accogliente-in-centro.jpg",
        "image_original_name" => "monolocale accogliente in centro",
        "is_visible" => true
    ],
    [
        "user_id" => 3,
        "title" => "Appartamento di lusso con vista panoramica",
        "slug" => "appartamento-di-lusso-con-vista-panoramica",
        "rooms" => 4,
        "beds" => 3,
        "bathrooms" => 3,
        "square_meters" => 170,
        "address" => "Via del Panorama 12, Firenze",
        "latitude" => 43.7696,
        "longitude" => 11.2558,
        "image_path" => "uploads/appartamento-di-lusso-con-vista-panoramica.jpg",
        "image_original_name" => "appartamento di lusso con vista panoramica",
        "is_visible" => true
    ],
    [
        "user_id" => 4,
        "title" => "Bilocale moderno e luminoso",
        "slug" => "bilocale-moderno-e-luminoso",
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "square_meters" => 65,
        "address" => "Via dei Fiori 25, Napoli",
        "latitude" => 40.8518,
        "longitude" => 14.2681,
        "image_path" => "uploads/bilocale-moderno-e-luminoso.jpg",
        "image_original_name" => "bilocale moderno e luminoso",
        "is_visible" => true
    ],
    [
        "user_id" => 4,
        "title" => "Appartamento con terrazza privata",
        "slug" => "appartamento-con-terrazza-privata",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 2,
        "square_meters" => 95,
        "address" => "Via delle Rose 5, Bari",
        "latitude" => 41.1256,
        "longitude" => 16.8661,
        "image_path" => "uploads/appartamento-con-terrazza-privata.jpg",
        "image_original_name" => "appartamento con terrazza privata",
        "is_visible" => true
    ],
    [
        "user_id" => 4,
        "title" => "Trilocale in pieno centro",
        "slug" => "trilocale-in-pieno-centro",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "square_meters" => 80,
        "address" => "Via Roma 22, Palermo",
        "latitude" => 38.1157,
        "longitude" => 13.3615,
        "image_path" => "uploads/trilocale-in-pieno-centro.jpg",
        "image_original_name" => "trilocale in pieno centro",
        "is_visible" => true
    ],
    [
        "user_id" => 3,
        "title" => "Appartamento con vista sul mare",
        "slug" => "appartamento-con-vista-sul-mare",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "square_meters" => 80,
        "address" => "Corso Vittorio Emanuele 12, Napoli",
        "latitude" => 40.8518,
        "longitude" => 14.2681,
        "image_path" => "uploads/appartamento-con-vista-sul-mare.jpg",
        "image_original_name" => "appartamento con vista sul mare",
        "is_visible" => true
    ],
    [
        "user_id" => 4,
        "title" => "Loft moderno nel centro di Milano",
        "slug" => "loft-moderno-nel-centro-di-milano",
        "rooms" => 1,
        "beds" => 1,
        "bathrooms" => 1,
        "square_meters" => 55,
        "address" => "Piazza della Repubblica 7, Milano",
        "latitude" => 45.4845,
        "longitude" => 9.2000,
        "image_path" => "uploads/loft-moderno-nel-centro-di-milano.jpg",
        "image_original_name" => "loft moderno nel centro di milano",
        "is_visible" => true
    ],
    [
        "user_id" => 4,
        "title" => "Appartamento elegante a Firenze",
        "slug" => "appartamento-elegante-a-firenze",
        "rooms" => 2,
        "beds" => 2,
        "bathrooms" => 1,
        "square_meters" => 70,
        "address" => "Piazza del Duomo 1, Firenze",
        "latitude" => 43.7696,
        "longitude" => 11.2558,
        "image_path" => "uploads/appartamento-elegante-a-firenze.jpg",
        "image_original_name" => "appartamento elegante a firenze",
        "is_visible" => true
    ],
    [
        "user_id" => 4,
        "title" => "Appartamento in zona tranquilla",
        "slug" => "appartamento-in-zona-tranquilla",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "square_meters" => 75,
        "address" => "Via della Libertà 20, Palermo",
        "latitude" => 38.1157,
        "longitude" => 13.3615,
        "image_path" => "uploads/appartamento-in-zona-tranquilla.jpg",
        "image_original_name" => "appartamento in zona tranquilla",
        "is_visible" => true
    ],
    [
        "user_id" => 4,
        "title" => "Trilocale con terrazzo a Roma",
        "slug" => "trilocale-con-terrazzo-a-roma",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 2,
        "square_meters" => 100,
        "address" => "Via dei Fori Imperiali 25, Roma",
        "latitude" => 41.8947,
        "longitude" => 12.4818,
        "image_path" => "uploads/trilocale-con-terrazzo-a-roma.jpg",
        "image_original_name" => "trilocale con terrazzo a roma",
        "is_visible" => true
    ],
    [
        "user_id" => 3,
        "title" => "Appartamento in campagna",
        "slug" => "appartamento-in-campagna",
        "rooms" => 4,
        "beds" => 3,
        "bathrooms" => 2,
        "square_meters" => 120,
        "address" => "Strada del Vino 12, Siena",
        "latitude" => 43.3188,
        "longitude" => 11.3308,
        "image_path" => "uploads/appartamento-in-campagna.jpg",
        "image_original_name" => "appartamento in campagna",
        "is_visible" => true
    ],
    [
        "user_id" => 4,
        "title" => "Bilocale ristrutturato a Torino",
        "slug" => "bilocale-ristrutturato-a-torino",
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "square_meters" => 65,
        "address" => "Via Roma 45, Torino",
        "latitude" => 45.0703,
        "longitude" => 7.6869,
        "image_path" => "uploads/bilocale-ristrutturato-a-torino.jpg",
        "image_original_name" => "bilocale ristrutturato a torino",
        "is_visible" => true
    ],
    [
        "user_id" => 3,
        "title" => "Casa vacanze al lago",
        "slug" => "casa-vacanze-al-lago",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "square_meters" => 90,
        "address" => "Lungolago 15, Como",
        "latitude" => 45.5906,
        "longitude" => 9.0877,
        "image_path" => "uploads/casa-vacanze-al-lago.jpg",
        "image_original_name" => "casa vacanze al lago",
        "is_visible" => true
    ],
    [
        "user_id" => 4,
        "title" => "Villa con giardino a Bergamo",
        "slug" => "villa-con-giardino-a-bergamo",
        "rooms" => 6,
        "beds" => 5,
        "bathrooms" => 4,
        "square_meters" => 300,
        "address" => "Via della Libertà 8, Bergamo",
        "latitude" => 45.6980,
        "longitude" => 9.6705,
        "image_path" => "uploads/villa-con-giardino-a-bergamo.jpg",
        "image_original_name" => "villa con giardino a bergamo",
        "is_visible" => true
    ],
    [
        "user_id" => 4,
        "title" => "Appartamento moderno in centro città",
        "slug" => "appartamento-moderno-in-centro-citta",
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "square_meters" => 70,
        "address" => "Piazza Garibaldi 1, Napoli",
        "latitude" => 40.8522,
        "longitude" => 14.2681,
        "image_path" => "uploads/appartamento-moderno-in-centro-citta.jpg",
        "image_original_name" => "appartamento moderno in centro citta",
        "is_visible" => true
    ],
    [
        "user_id" => 4,
        "title" => "Attico con vista panoramica",
        "slug" => "attico-con-vista-panoramica",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 2,
        "square_meters" => 120,
        "address" => "Via dei Colli 10, Bologna",
        "latitude" => 44.4949,
        "longitude" => 11.3426,
        "image_path" => "uploads/attico-con-vista-panoramica.jpg",
        "image_original_name" => "attico con vista panoramica",
        "is_visible" => true
    ],
    [
        "user_id" => 3,
        "title" => "Monolocale a Rimini",
        "slug" => "monolocale-a-rimini",
        "rooms" => 1,
        "beds" => 1,
        "bathrooms" => 1,
        "square_meters" => 35,
        "address" => "Corso d'Augusto 5, Rimini",
        "latitude" => 44.0679,
        "longitude" => 12.5674,
        "image_path" => "uploads/monolocale-a-rimini.jpg",
        "image_original_name" => "monolocale a rimini",
        "is_visible" => true
    ],
    [
        "user_id" => 3,
        "title" => "Appartamento in centro storico",
        "slug" => "appartamento-in-centro-storico",
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "square_meters" => 50,
        "address" => "Via delle Belle Arti 4, Bologna",
        "latitude" => 44.4949,
        "longitude" => 11.3426,
        "image_path" => "uploads/appartamento-in-centro-storico.jpg",
        "image_original_name" => "appartamento in centro storico",
        "is_visible" => true
    ],
    [
        "user_id" => 4,
        "title" => "Villa storica in campagna",
        "slug" => "villa-storica-in-campagna",
        "rooms" => 7,
        "beds" => 6,
        "bathrooms" => 5,
        "square_meters" => 350,
        "address" => "Via dei Cipressi 3, Arezzo",
        "latitude" => 43.4641,
        "longitude" => 11.8746,
        "image_path" => "uploads/villa-storica-in-campagna.jpg",
        "image_original_name" => "villa storica in campagna",
        "is_visible" => true
    ],
    [
        "user_id" => 4,
        "title" => "Casa in montagna",
        "slug" => "casa-in-montagna",
        "rooms" => 4,
        "beds" => 3,
        "bathrooms" => 2,
        "square_meters" => 160,
        "address" => "Strada del Sole 5, Trento",
        "latitude" => 46.0743,
        "longitude" => 11.1216,
        "image_path" => "uploads/casa-in-montagna.jpg",
        "image_original_name" => "casa in montagna",
        "is_visible" => true
    ],
];
