<?php

$services = [
    'WiFi',
    'Posto Macchina',
    'Piscina',
    'Portineria',
    'Sauna',
    'Vista Mare',
    'Aria Condizionata',
    'Riscaldamento',
    'TV via Cavo',
    'Cucina Completa',
    'Lavastoviglie',
    'Lavatrice',
    'Asciugatrice',
    'Balcone',
    'Giardino Privato',
    'Barbecue',
    'Vasca Idromassaggio',
    'Camino',
    'Accesso Disabili',
    'Animali Ammessi',
    'Palestra',
    'Spa',
    'Servizio in Camera',
    'Colazione Inclusa',
    'Ristorante in Loco',
    'Navetta Aeroporto',
    'Parco Giochi',
    'Deposito Bagagli',
    'Parcheggio Bici',
    'Noleggio Auto',
    'Servizio di Pulizia',
    'Reception 24 Ore',
    'Cassaforte',
    'Frigorifero',
    'Mini Bar',
    'Servizio Lavanderia',
    'Cambio Biancheria',
    'Vista Montagna',
    'Vicino alla Spiaggia',
    'Accesso alla Pista Ciclabile'
];
